site_name: Rajesh Angular Document 
# https://<your-username>.github.io/<repo-name>/files/angular-ag-grid.docx
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
nav:
 - Home: index.md
 - Angular:
   - Binding: angular/binding.md
   - Input: angular/input.md
   - OutPut: angular/output.md
   - ViewChild: angular/viewchild.md
   - FormArray: angular/formarray.md  
   - ReactiveForms: angular/reactiveForm.md  
   - Signal: angular/signal.md
   - MatDialog: angular/matdilog.md
   - SwalFire: angular/swal.md
   - ClickEvent: angular/clickEvent.md
   - GitHub: angular/github.md
   - ShortCutKeys: angular/shortcutkeys.md
  
 - AG- GRID:
   - AG-Grid: Ag-grid/ag-grid.md  
   - CellRender: Ag-grid/cellrender.md
 - ONLY IMAGES:
   - images: Only-images/onlyimages.md  
 - PDF Files:
   - Files: files/file.md  
   
